site_name: Harmony
site_url: https://sheldoncoder1337.github.io/
site_author: jialecai
site_description: Personal Blog by Sheldon
copyright: 'Copyright &copy; 2025 <a href="https://sheldoncoder1337.github.io">jialecai</a>'
repo_url: https://github.com/sheldoncoder1337.github.io/

nav:
  - Home: "index.md"
  - ComputerArchitecture:
    - 00-Introduction: "cs01-computer-architecture/00-introduction.md"
  - DataStructure:
    - 00-Introduction: "cs02-data-structure/00-introduction.md"
  - OperatingSystem:
    - 00-Introduction: "cs03-operating-system/00-introduction.md"
  - ComputerNetwork:
    - 00-Introduction: "cs04-computer-network/00-introduction.md"
  - Database:
    - 00-Introduction: "cs05-database-system/00-introduction.md"
  - MachineLearning:
    - 00-Introduction: "cs06-machine-learning/00-introduction.md"
  - Deeplearning:
    - 00-Introduction: "cs07-deep-learning/00-introduction.md"
    - 16-asr.md: "cs07-deep-learning/16-asr.md"
  - SoftwareEngineering:
    - 00-Introduction: "cs08-software-engineering/00-introduction.md"
    - 01-CookC: "cs08-software-engineering/01-cookc.md"
  - Math:
    - 00-Introduction: "math/00-introduction.md"
  - Handbook:
    - Markdown: "handbook/markdown.md"
    - Powershell: "handbook/powershell.md"
    - Docker: "handbook/docker.md"
    - Git: "handbook/git.md"
    - WSL: "handbook/wsl.md"
    - UV: "handbook/uv.md"

theme:
  name: material
  language: en
  features:
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.footnote.tooltips
    - content.tooltips
  icon:
    annotation: material/arrow-right-circle 
  palette:
    - scheme: default  # Toggle light mode
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate    # Toggle dark mode
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

markdown_extensions:
  - abbr
  - def_list
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
    - javascripts/katex.js
    - https://unpkg.com/katex@0/dist/katex.min.js
    - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  copyright: Copyright
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sheldoncoder1337
  # alternate:
  #   - name: English
  #     link: http://127.0.0.1:8000/
  #     lang: en
  #   - name: 简体中文
  #     link: http://127.0.0.1:8000/
  #     lang: zh
      
# plugins:
#   - glightbox